# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins_a', '0002_auto_20180321_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer', to='joins_a.Join')),
                ('email_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_invite', to='joins_a.Join')),
                ('friends', models.ManyToManyField(blank=True, null=True, related_name='Friend', to='joins_a.Join')),
            ],
        ),
    ]
