# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
